export const solutions=[
 {id:'presence',name:'Presencia Digital',tagline:'Una presencia profesional para que te encuentren, entiendan lo que ofrecés y puedan contactarte con facilidad.',description:'Ordenamos tu propuesta y la convertimos en una experiencia clara para la persona que llega por primera vez.',links:[['Landing profesional','soluciones/landing-profesional.html'],['Sitio institucional','soluciones/sitio-institucional.html']]},
 {id:'sales',name:'Ventas Digitales',tagline:'Mostrá productos, recibí consultas o pedidos sin sumar complejidad innecesaria.',description:'Puede empezar con un catálogo compartible y pedidos por WhatsApp. Una tienda completa queda como evolución bajo consulta.',links:[['Catálogo digital','soluciones/catalogo-digital.html']]},
 {id:'management',name:'Gestión del Negocio',tagline:'Ordená turnos, información y tareas internas alrededor de tu operación.',description:'Una agenda o un panel específico puede ser el primer módulo. Stock, ventas y reportes se evalúan como evoluciones, no como un ERP prometido.',links:[['Turnos y reservas','soluciones/turnos-reservas.html'],['Software a medida','soluciones/software-a-medida.html']]},
 {id:'automation',name:'Automatización de Procesos',tagline:'Reducí cargas manuales, pasos repetidos y errores conectando lo que ya usás.',description:'Formularios, avisos, planillas, WhatsApp o procesamiento de información: la tecnología se elige después de entender la tarea.',links:[['Automatizaciones','soluciones/automatizaciones.html']]},
 {id:'custom',name:'Soluciones a Medida',tagline:'Cuando el problema no encaja en un paquete, diseñamos alrededor de tu forma de trabajar.',description:'Sistemas internos, paneles e integraciones se definen por etapas, con una primera versión concreta y un alcance acordado.',links:[['Software a medida','soluciones/software-a-medida.html']]},
 {id:'maintenance',name:'Mantenimiento y Evolución',tagline:'Corregí, optimizá o ampliá una solución para que siga acompañando al negocio.',description:'El soporte se toma responsablemente cuando el proyecto puede comprenderse, probarse y mantenerse.',links:[['Mantenimiento y evolución','soluciones/mantenimiento-evolucion.html']]}
];

export const industries={
 kioscos:{title:'Kioscos y comercios',summary:'Cuando precios, pedidos y movimientos viven entre mensajes y anotaciones, una solución posible puede comenzar por hacer visible y ordenable lo cotidiano.',problems:['Productos y precios dispersos','Pedidos por mensajes','Stock poco visible','Ventas sin una lectura clara'],solutions:[['Catálogo digital','soluciones/catalogo-digital.html'],['Software a medida','soluciones/software-a-medida.html']],starts:['Presencia y catálogo','Catálogo más una gestión inicial','Proyecto adaptado por etapas']},
 corralones:{title:'Ferreterías y corralones',summary:'Muchos productos y consultas repetidas pueden abordarse con una presencia clara, un catálogo o un flujo de presupuestos, según el alcance.',problems:['Consultas repetidas','Presupuestos manuales','Información de stock','Pedidos difíciles de seguir'],solutions:[['Sitio institucional','soluciones/sitio-institucional.html'],['Catálogo digital','soluciones/catalogo-digital.html']],starts:['Sitio y consulta de presupuesto','Catálogo con pedidos','Gestión como evolución']},
 gastronomia:{title:'Gastronomía y rotiserías',summary:'Un menú cambiante y los pedidos por varios canales pueden simplificarse empezando por una experiencia de consulta y pedido.',problems:['Menú desactualizado','Pedidos desordenados','Retiro o envío','Disponibilidad cambiante'],solutions:[['Catálogo digital','soluciones/catalogo-digital.html'],['Automatizaciones','soluciones/automatizaciones.html']],starts:['Menú digital','Pedidos por WhatsApp','Gestión simple bajo alcance']},
 inmobiliarias:{title:'Inmobiliarias',summary:'Una solución posible puede ordenar la presentación de propiedades y reducir la dependencia para actualizar contenido.',problems:['Propiedades desactualizadas','Fotos y datos difíciles de gestionar','Consultas sin contexto','Dependencia para cada cambio'],solutions:[['Sitio institucional','soluciones/sitio-institucional.html'],['Software a medida','soluciones/software-a-medida.html']],starts:['Sitio profesional','Propiedades y filtros','Panel administrable como evolución']},
 peluquerias:{title:'Peluquerías',summary:'La coordinación manual puede comenzar a simplificarse con una presencia clara y una agenda ajustada a servicios y horarios.',problems:['Coordinación por mensajes','Huecos en agenda','Consultas repetidas','Recordatorios manuales'],solutions:[['Landing profesional','soluciones/landing-profesional.html'],['Turnos y reservas','soluciones/turnos-reservas.html']],starts:['Landing y contacto','Agenda inicial','Reservas y recordatorios según alcance']},
 profesionales:{title:'Profesionales y estudios',summary:'Una presencia ordenada, formularios o turnos pueden dar un primer paso concreto sin sobredimensionar la solución.',problems:['Poca presencia digital','Consultas desordenadas','Agenda manual','Información dispersa'],solutions:[['Landing profesional','soluciones/landing-profesional.html'],['Turnos y reservas','soluciones/turnos-reservas.html'],['Automatizaciones','soluciones/automatizaciones.html']],starts:['Presencia profesional','Contacto y formularios','Agenda o automatización']},
 alojamientos:{title:'Alojamientos y turismo',summary:'La presentación visual y las consultas de disponibilidad pueden organizarse con un sitio y un recorrido de reserva según el alcance.',problems:['Presentación visual débil','Disponibilidad por mensaje','Consultas internacionales','Información repetida'],solutions:[['Sitio institucional','soluciones/sitio-institucional.html'],['Turnos y reservas','soluciones/turnos-reservas.html']],starts:['Sitio y galería','Consulta de disponibilidad','Contenido bilingüe bajo alcance']},
 distribuidoras:{title:'Distribuidoras y mayoristas',summary:'Los catálogos extensos y pedidos recurrentes pueden comenzar por una consulta ordenada y evolucionar hacia herramientas internas.',problems:['Catálogos extensos','Pedidos recurrentes','Clientes y stock','Compras difíciles de seguir'],solutions:[['Catálogo digital','soluciones/catalogo-digital.html'],['Software a medida','soluciones/software-a-medida.html']],starts:['Catálogo y pedidos','Panel de clientes','Stock y compras como evolución']}
};

export const advisorSteps=[
 {key:'activity',question:'¿Qué tipo de actividad tenés?',options:[['commerce','Comercio'],['service','Servicios'],['professional','Profesional o estudio'],['operation','Operación o distribución'],['idea','Estoy desarrollando una idea'],['browse','Solo estoy mirando']]},
 {key:'goal',question:'¿Qué te gustaría mejorar primero?',options:[['presence','Que me encuentren y contacten'],['sales','Mostrar productos o vender'],['organize','Organizar turnos o tareas'],['manual','Ahorrar trabajo manual'],['specific','Necesito algo específico'],['unsure','No estoy seguro']]},
 {key:'today',question:'¿Cómo lo resolvés hoy?',options:[['whatsapp','WhatsApp'],['paper','Papeles'],['sheets','Planillas'],['oldweb','Una web desactualizada'],['separate','Varias herramientas separadas'],['none','Todavía no lo hago'],['other','Otro']]},
 {key:'start',question:'¿Cómo preferís empezar?',options:[['simple','Con una versión simple'],['complete','Con una solución más completa'],['compare','Quiero comparar opciones'],['explore','Solo quiero explorar']]}
];

export const getRecommendation=(answers)=>{
 const goal=answers.goal;
 if(answers.activity==='browse'||answers.start==='explore')return {title:'Explorá sin apuro',text:'Podés recorrer las experiencias y las familias para entender qué caminos existen. El orientador no envía ni guarda tus respuestas.',href:'#experiencias',label:'Explorar experiencias'};
 if(goal==='sales')return {title:'Catálogo digital',text:'Podrías empezar mostrando productos y preparando pedidos o consultas por WhatsApp. Es más simple que una tienda completa y puede ampliarse después.',href:'soluciones/catalogo-digital.html',label:'Ver catálogo digital'};
 if(goal==='organize'&&(answers.activity==='service'||answers.activity==='professional'))return {title:'Turnos y reservas',text:'Una agenda inicial podría reducir coordinación por mensajes. Disponibilidad, recordatorios o panel pueden sumarse según el alcance.',href:'soluciones/turnos-reservas.html',label:'Ver turnos y reservas'};
 if(goal==='manual')return {title:'Automatización de procesos',text:'Conviene identificar primero la carga repetitiva y conectar solo los pasos necesarios. Puede comenzar con un formulario, registro o aviso.',href:'soluciones/automatizaciones.html',label:'Ver automatizaciones'};
 if(goal==='specific'||answers.activity==='operation')return {title:'Software a medida',text:'Tu caso merece un diagnóstico breve. Podemos definir una primera versión acotada alrededor de la operación y dejar una evolución posible.',href:'soluciones/software-a-medida.html',label:'Ver software a medida'};
 if(goal==='presence'||answers.today==='oldweb')return {title:answers.start==='complete'?'Sitio institucional':'Landing profesional',text:'Una presencia clara puede ayudarte a explicar qué hacés y convertir visitas en consultas. El alcance puede empezar en una sola página o crecer por secciones.',href:answers.start==='complete'?'soluciones/sitio-institucional.html':'soluciones/landing-profesional.html',label:'Ver la solución'};
 return {title:'Comparemos un primer paso',text:'Por lo que contás, puede servir una conversación corta para separar lo urgente de lo que puede esperar. También podés seguir explorando sin compromiso.',href:'#familias',label:'Comparar soluciones'};
};
